## Índices

#### Crear una serie con el tipo de índice DatetimeIndex

In [2]:
import pandas as pd

ind = pd.DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04'])

ventas = [2350, 3150, 4200, 1175]

serie = pd.Series(ventas, index = ind)
serie

2023-09-01    2350
2023-09-02    3150
2023-09-03    4200
2023-09-04    1175
dtype: int64

In [3]:
serie.index

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04'], dtype='datetime64[us]', freq=None)

In [4]:
serie.index[3]

Timestamp('2023-09-04 00:00:00')

### Crear un DataFrame

In [6]:
ventas2 = [1923, 2413, 1097, 3213]

dicc = {'suc1' : ventas, 'suc2' : ventas2}

df_ventas = pd.DataFrame.from_dict(data = dicc).set_index(ind)
df_ventas.head()

            suc1  suc2
2023-09-01  2350  1923
2023-09-02  3150  2413
2023-09-03  4200  1097
2023-09-04  1175  3213

In [7]:
df_ventas.index

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04'], dtype='datetime64[us]', freq=None)

### Crear una Serie de Tiempo al momento de la lectura

In [ ]:
# INDICES SIN FORMATOS DE FECHA Y CON FORMATO OBJECT

weather = pd.read_csv('datos/weather_dataset.csv')
weather.head()

,datetime,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
0,2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
1,2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2,2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
3,2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
4,2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

In [15]:
weather['datetime'].dtypes

In [ ]:
# OPCION 1

weather = pd.read_csv('datos/weather_dataset.csv',
                        parse_dates = ['datetime'], # que columnas convertir a TimeStamp
                        index_col = 'datetime')     # especificar que columna se va a usar como indice
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

In [18]:
# OPCION 2

weather = pd.read_csv('datos/weather_dataset.csv')
weather['datetime'] = pd.to_datetime(weather['datetime'])
weather = weather.set_index('datetime')
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

### Ejemplo práctico

In [21]:
temps = pd.read_csv('datos/serie_temps.csv')
temps.head()

       fechas  horas  temperaturas
0  09/01/2023  05:25          27.0
1  09/02/2023  04:53          26.6
2  09/03/2023  13:32          28.2
3  09/04/2023  12:23          25.3

In [22]:
temps['fechas'].dtypes

In [ ]:
# Fechas y horas separadas y con formatos object
temps = pd.read_csv('datos/serie_temps.csv',
                    parse_dates = ['fechas', 'horas'])
temps.head()

/tmp/ipykernel_20904/1430699439.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temps = pd.read_csv('datos/serie_temps.csv',

      fechas               horas  temperaturas
0 2023-09-01 2026-04-15 05:25:00          27.0
1 2023-09-02 2026-04-15 04:53:00          26.6
2 2023-09-03 2026-04-15 13:32:00          28.2
3 2023-09-04 2026-04-15 12:23:00          25.3

In [40]:
# Combinar fechas y horas en formato adecuado
temps = pd.read_csv('datos/serie_temps.csv')

formato = '%m/%d/%Y %H:%M'
temps['fecha_hora'] = pd.to_datetime(temps['fechas'] + ' ' + temps['horas'], format = formato)
temps.head()

       fechas  horas  temperaturas          fecha_hora
0  09/01/2023  05:25          27.0 2023-09-01 05:25:00
1  09/02/2023  04:53          26.6 2023-09-02 04:53:00
2  09/03/2023  13:32          28.2 2023-09-03 13:32:00
3  09/04/2023  12:23          25.3 2023-09-04 12:23:00

In [41]:
temps = temps.set_index('fecha_hora')
temps = temps.drop(columns = ['fechas', 'horas'])
temps.head()

                     temperaturas
fecha_hora
2023-09-01 05:25:00          27.0
2023-09-02 04:53:00          26.6
2023-09-03 13:32:00          28.2
2023-09-04 12:23:00          25.3

### Representaciónes alternativas - PeriodIndex y TimeDeltaIndex

### PeriodIndex

Expresar el indice de la serie de tiempo como intervalos de tiempo regulares (semanas, meses, años)

In [43]:
import pandas as pd

weather = pd.read_csv('datos/weather_dataset.csv',
                        parse_dates = ['datetime'],
                        index_col = 'datetime')
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

In [45]:
ind = weather.index
ind

DatetimeIndex(['2009-01-01 01:00:00', '2009-01-01 02:00:00',
               '2009-01-01 03:00:00', '2009-01-01 04:00:00',
               '2009-01-01 05:00:00', '2009-01-01 06:00:00',
               '2009-01-01 07:00:00', '2009-01-01 08:00:00',
               '2009-01-01 09:00:00', '2009-01-01 10:00:00',
               ...
               '2009-02-21 08:00:00', '2009-02-21 09:00:00',
               '2009-02-21 10:00:00', '2009-02-21 11:00:00',
               '2009-02-21 12:00:00', '2009-02-21 13:00:00',
               '2009-02-21 14:00:00', '2009-02-21 15:00:00',
               '2009-02-21 16:00:00', '2009-02-21 17:00:00'],
              dtype='datetime64[us]', name='datetime', length=1241, freq=None)

In [48]:
ind.to_period('W')

PeriodIndex(['2008-12-29/2009-01-04', '2008-12-29/2009-01-04',
             '2008-12-29/2009-01-04', '2008-12-29/2009-01-04',
             '2008-12-29/2009-01-04', '2008-12-29/2009-01-04',
             '2008-12-29/2009-01-04', '2008-12-29/2009-01-04',
             '2008-12-29/2009-01-04', '2008-12-29/2009-01-04',
             ...
             '2009-02-16/2009-02-22', '2009-02-16/2009-02-22',
             '2009-02-16/2009-02-22', '2009-02-16/2009-02-22',
             '2009-02-16/2009-02-22', '2009-02-16/2009-02-22',
             '2009-02-16/2009-02-22', '2009-02-16/2009-02-22',
             '2009-02-16/2009-02-22', '2009-02-16/2009-02-22'],
            dtype='period[W-SUN]', name='datetime', length=1241)

In [51]:
ind.to_period('Y')

PeriodIndex(['2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009',
             '2009', '2009',
             ...
             '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009',
             '2009', '2009'],
            dtype='period[Y-DEC]', name='datetime', length=1241)

### TimeDeltaIndex

Representa el tiempo que ha transcurrido con respecto a un tiempo de referencia

In [52]:
ind - ind[0]

TimedeltaIndex([ '0 days 00:00:00',  '0 days 01:00:00',  '0 days 02:00:00',
                 '0 days 03:00:00',  '0 days 04:00:00',  '0 days 05:00:00',
                 '0 days 06:00:00',  '0 days 07:00:00',  '0 days 08:00:00',
                 '0 days 09:00:00',
                ...
                '51 days 07:00:00', '51 days 08:00:00', '51 days 09:00:00',
                '51 days 10:00:00', '51 days 11:00:00', '51 days 12:00:00',
                '51 days 13:00:00', '51 days 14:00:00', '51 days 15:00:00',
                '51 days 16:00:00'],
               dtype='timedelta64[us]', name='datetime', length=1241, freq=None)