### Técnicas de slicing
Extraer una porción de la serie tomando como referencia la variable temporal

In [1]:
import pandas as pd

weather = pd.read_csv('datos/weather_dataset.csv',
                        parse_dates = ['datetime'],
                        index_col = 'datetime')
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

In [2]:
weather.loc['2009-01-01 02:00:00']

p (mbar)            996.62
T (degC)             -8.88
Tpot (K)            264.54
Tdew (degC)          -9.77
rh (%)               93.20
VPmax (mbar)          3.12
VPact (mbar)          2.90
VPdef (mbar)          0.21
sh (g/kg)             1.81
H2OC (mmol/mol)       2.91
rho (g/m**3)       1312.25
wv (m/s)              0.25
max. wv (m/s)         0.63
wd (deg)            190.30
Name: 2009-01-01 02:00:00, dtype: float64

In [4]:
weather.loc['2009-01-01 15:00:00':'2009-01-02 06:00:00']

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 15:00:00,999.88,-5.69,267.48,-7.00,90.4,3.99,3.61,0.38,2.25,3.61,1300.51,1.17,1.88,134.90
2009-01-01 16:00:00,999.94,-5.40,267.76,-6.86,89.4,4.08,3.65,0.43,2.27,3.65,1299.17,1.40,2.13,145.50
2009-01-01 17:00:00,1000.17,-5.37,267.78,-6.82,89.4,4.09,3.66,0.43,2.28,3.66,1299.27,0.85,1.63,142.20
2009-01-01 18:00:00,1000.16,-5.25,267.90,-6.75,89.1,4.13,3.68,0.45,2.29,3.68,1298.68,0.55,1.00,183.70
2009-01-01 19:00:00,1000.22,-5.11,268.03,-6.57,89.4,4.17,3.73,0.44,2.32,3.73,1298.07,0.41,0.75,176.70
2009-01-01 20:00:00,1000.22,-4.90,268.24,-6.38,89.3,4.24,3.79,0.45,2.36,3.78,1297.05,0.68,1.13,195.20
2009-01-01 21:00:00,1000.19,-4.80,268.35,-6.14,90.2,4.27,3.85,0.42,2.40,3.85,1296.45,0.44,0.75,206.30
2009-01-01 22:00:00,1000.00,-4.50,268.66,-5.82,90.4,4.37,3.95,0.42,2.46,3.95,1294.72,0.33,0.63,175.70
2009-01-01 23:00:00,999.77,-4.47,268.71,-5.84,90.1,4.38,3.95,0.43,2.46,3.95,1294.29,0.65,1.00,219.30
2009-01-02 00:00:00,999.59,-4.54,268.65,-5.46,93.2,4.36,4.06,0.30,2.53,4.06,1294.33,0.41,0.88,155.00
2009-01-02 01:00:00,999.34,-4.44,268.77,-5.19,94.4,4.39,4.15,0.25,2.58,4.15,1293.47,0.28,1.00,148.10
2009-01-02 02:00:00,998.93,-4.29,268.95,-5.04,94.5,4.44,4.20,0.24,2.62,4.20,1292.22,0.49,0.88,209.80
2009-01-02 03:00:00,998.69,-4.45,268.81,-5.15,94.8,4.39,4.16,0.23,2.59,4.16,1292.69,0.65,1.00,203.30
2009-01-02 04:00:00,998.32,-4.58,268.71,-5.22,95.2,4.34,4.14,0.21,2.58,4.14,1292.83,0.77,1.38,190.20
2009-01-02 05:00:00,998.10,-4.96,268.34,-5.50,96.0,4.22,4.05,0.17,2.53,4.06,1294.44,0.79,1.25,22.22
2009-01-02 06:00:00,998.00,-4.43,268.88,-4.94,96.2,4.39,4.23,0.17,2.64,4.23,1291.66,0.81,2.13,40.88

In [5]:
weather.loc['2009-01-01':'2009-01-02']

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.70
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.30
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.20
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.00
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.00
2009-01-01 06:00:00,997.71,-9.67,263.66,-10.62,92.7,2.93,2.71,0.21,1.69,2.72,1317.71,0.05,0.50,146.00
2009-01-01 07:00:00,998.33,-9.17,264.12,-10.10,92.9,3.04,2.83,0.22,1.76,2.83,1315.98,2.08,2.88,348.80
2009-01-01 08:00:00,999.17,-8.10,265.12,-9.05,92.8,3.31,3.07,0.24,1.92,3.08,1311.65,0.72,1.25,213.90
2009-01-01 09:00:00,999.69,-7.66,265.52,-8.84,91.2,3.43,3.13,0.30,1.95,3.13,1310.14,0.34,0.63,202.20
2009-01-01 10:00:00,1000.27,-7.04,266.10,-8.17,91.6,3.60,3.30,0.30,2.05,3.29,1307.76,1.45,3.00,292.60
2009-01-01 11:00:00,1000.87,-7.41,265.68,-8.66,90.7,3.50,3.17,0.33,1.97,3.17,1310.43,1.91,3.38,269.60
2009-01-01 12:00:00,1000.30,-6.87,266.27,-8.28,89.6,3.64,3.27,0.38,2.03,3.26,1306.98,1.84,2.63,184.40
2009-01-01 13:00:00,1000.03,-5.89,267.27,-7.46,88.6,3.93,3.48,0.45,2.17,3.48,1301.73,0.57,1.25,187.30
2009-01-01 14:00:00,999.81,-5.94,267.24,-7.43,89.1,3.92,3.49,0.43,2.17,3.49,1301.67,1.25,2.00,144.00
2009-01-01 15:00:00,999.88,-5.69,267.48,-7.00,90.4,3.99,3.61,0.38,2.25,3.61,1300.51,1.17,1.88,134.90
2009-01-01 16:00:00,999.94,-5.40,267.76,-6.86,89.4,4.08,3.65,0.43,2.27,3.65,1299.17,1.40,2.13,145.50
2009-01-01 17:00:00,1000.17,-5.37,267.78,-6.82,89.4,4.09,3.66,0.43,2.28,3.66,1299.27,0.85,1.63,142.20
2009-01-01 18:00:00,1000.16,-5.25,267.90,-6.75,89.1,4.13,3.68,0.45,2.29,3.68,1298.68,0.55,1.00,183.70
2009-01-01 19:00:00,1000.22,-5.11,268.03,-6.57,89.4,4.17,3.73,0.44,2.32,3.73,1298.07,0.41,0.75,176.70
2009-01-01 20:00:00,1000.22,-4.90,268.24,-6.38,89.3,4.24,3.79,0.45,2.36,3.78,1297.05,0.68,1.13,195.20
2009-01-01 21:00:00,1000.19,-4.80,268.35,-6.14,90.2,4.27,3.85,0.42,2.40,3.85,1296.45,0.44,0.75,206.30
2009-01-01 22:00:00,1000.00,-4.50,268.66,-5.82,90.4,4.37,3.95,0.42,2.46,3.95,1294.72,0.33,0.63,175.70
2009-01-01 23:00:00,999.77,-4.47,268.71,-5.84,90.1,4.38,3.95,0.43,2.46,3.95,1294.29,0.65,1.00,219.30
2009-01-02 00:00:00,999.59,-4.54,268.65,-5.46,93.2,4.36,4.06,0.30,2.53,4.06,1294.33,0.41,0.88,155.00
2009-01-02 01:00:00,999.34,-4.44,268.77,-5.19,94.4,4.39,4.15,0.25,2.58,4.15,1293.47,0.28,1.00,148.10
2009-01-02 02:00:00,998.93,-4.29,268.95,-5.04,94.5,4.44,4.20,0.24,2.62,4.20,1292.22,0.49,0.88,209.80
2009-01-02 03:00:00,998.69,-4.45,268.81,-5.15,94.8,4.39,4.16,0.23,2.59,4.16,1292.69,0.65,1.00,203.30
2009-01-02 04:00:00,998.32,-4.58,268.71,-5.22,95.2,4.34,4.14,0.21,2.58,4.14,1292.83,0.77,1.38,190.20
2009-01-02 05:00:00,998.10,-4.96,268.34,-5.50,96.0,4.22,4.05,0.17,2.53,4.06,1294.44,0.79,1.25,22.22
2009-01-02 06:00:00,998.00,-4.43,268.88,-4.94,96.2,4.39,4.23,0.17,2.64,4.23,1291.66,0.81,2.13,40.88
2009-01-02 07:00:00,998.17,-4.28,269.02,-4.89,95.5,4.44,4.24,0.20,2.65,4.25,1291.15,0.53,1.13,156.40
2009-01-02 08:00:00,998.18,-4.33,268.97,-5.04,94.8,4.43,4.20,0.23,2.62,4.20,1291.44,1.64,2.38,178.70
2009-01-02 09:00:00,998.35,-4.13,269.16,-4.97,93.8,4.49,4.22,0.28,2.63,4.22,1290.68,1.32,1.88,184.50
2009-01-02 10:00:00,998.65,-3.93,269.34,-4.99,92.3,4.56,4.21,0.35,2.63,4.22,1290.10,1.83,2.25,141.70
2009-01-02 11:00:00,998.98,-3.62,269.62,-4.68,92.3,4.67,4.31,0.36,2.69,4.32,1288.99,1.21,1.63,141.50
2009-01-02 12:00:00,998.91,-3.12,270.13,-4.50,90.1,4.85,4.37,0.48,2.73,4.38,1286.47,1.54,2.00,127.00
2009-01-02 13:00:00,998.59,-2.53,270.74,-4.23,88.0,5.07,4.46,0.61,2.78,4.47,1283.22,0.92,1.50,129.40
2009-01-02 14:00:00,998.73,-2.56,270.70,-4.29,87.8,5.06,4.44,0.62,2.77,4.45,1283.56,0.73,1.25,42.40
2009-01-02 15:00:00,998.87,-2.12,271.12,-4.00,86.9,5.22,4.54,0.68,2.83,4.54,1281.64,0.47,1.00,336.30
2009-01-02 16:00:00,999.59,-2.76,270.43,-4.22,89.6,4.98,4.46,0.52,2.78,4.46,1285.63,2.91,4.13,11.99
2009-01-02 17:00:00,1000.21,-2.88,270.26,-4.43,89.0,4.94,4.39,0.54,2.74,4.39,1287.04,1.52,2.88,7.05
2009-01-02 18:00:00,1000.74,-3.07,270.03,-4.14,92.3,4.87,4.49,0.37,2.80,4.49,1288.58,2.97,4.63,12.56
2009-01-02 19:00:00,1001.27,-3.34,269.72,-4.64,90.7,4.77,4.33,0.44,2.69,4.32,1290.63,3.07,4.50,14.34
2009-01-02 20:00:00,1001.83,-3.30,269.72,-4.29,92.8,4.79,4.44,0.34,2.76,4.43,1291.08,2.89,4.00,24.28
2009-01-02 21:00:00,1002.23,-3.49,269.50,-4.61,91.9,4.72,4.34,0.38,2.69,4.33,1292.57,2.48,3.88,14.31
2009-01-02 22:00:00,1002.39,-4.02,268.96,-5.58,88.8,4.53,4.03,0.51,2.50,4.02,1295.46,3.06,4.13,23.48
2009-01-02 23:00:00,1002.52,-4.38,268.59,-5.80,89.7,4.41,3.96,0.45,2.46,3.95,1297.39,0.74,1.38,354.00

In [7]:
weather.loc['2009-02']

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-02-01 00:00:00,989.86,-2.97,270.98,-5.04,85.5,4.91,4.19,0.71,2.64,4.24,1274.18,4.57,6.50,32.40
2009-02-01 01:00:00,989.11,-3.20,270.81,-5.30,85.3,4.82,4.11,0.71,2.59,4.16,1274.35,5.29,6.88,32.19
2009-02-01 02:00:00,988.61,-3.43,270.61,-6.53,79.0,4.74,3.74,0.99,2.36,3.79,1274.98,3.52,5.25,20.31
2009-02-01 03:00:00,987.99,-3.53,270.56,-6.12,82.1,4.70,3.86,0.84,2.43,3.91,1274.60,2.86,3.75,31.01
2009-02-01 04:00:00,987.23,-3.68,270.47,-6.16,82.8,4.65,3.85,0.80,2.43,3.90,1274.32,2.88,4.00,41.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-02-21 13:00:00,1001.53,1.43,274.47,0.57,94.0,6.77,6.37,0.41,3.96,6.36,1267.55,1.18,2.88,243.00
2009-02-21 14:00:00,1001.32,1.80,274.85,0.67,92.2,6.96,6.41,0.54,3.99,6.41,1265.56,1.67,3.25,254.60
2009-02-21 15:00:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.70
2009-02-21 16:00:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.80
2009-02-21 17:00:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.00

In [8]:
weather.loc['2009']

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-02-21 13:00:00,1001.53,1.43,274.47,0.57,94.0,6.77,6.37,0.41,3.96,6.36,1267.55,1.18,2.88,243.0
2009-02-21 14:00:00,1001.32,1.80,274.85,0.67,92.2,6.96,6.41,0.54,3.99,6.41,1265.56,1.67,3.25,254.6
2009-02-21 15:00:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.7
2009-02-21 16:00:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.8
2009-02-21 17:00:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.0