### Re muestreo -> asfreq() y resample()

Hacer un cambio en las frecuencias, pasar de anual a mensual, semanal, dia, horas...

In [5]:
import numpy as np
import pandas as pd

valores = np.random.randint(100, size=5)
indice = pd.date_range('2013-01-01', periods = 5, freq = '24h')
df = pd.DataFrame(data = {'valores' : valores}, index = indice)
df.head()

            valores
2013-01-01       91
2013-01-02       66
2013-01-03       32
2013-01-04       95
2013-01-05        9

In [8]:
df.index.freq

In [10]:
weather = pd.read_csv('datos/weather_dataset.csv',
                    parse_dates = ['datetime'], 
                    index_col = 'datetime')
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

### Hay que tratar determinar la frecuencia de los datos

In [ ]:
type(weather.index.freq) # no esta definida

NoneType

In [ ]:
weather.index # la frecuencia no está definida (None)

DatetimeIndex(['2009-01-01 01:00:00', '2009-01-01 02:00:00',
               '2009-01-01 03:00:00', '2009-01-01 04:00:00',
               '2009-01-01 05:00:00', '2009-01-01 06:00:00',
               '2009-01-01 07:00:00', '2009-01-01 08:00:00',
               '2009-01-01 09:00:00', '2009-01-01 10:00:00',
               ...
               '2009-02-21 08:00:00', '2009-02-21 09:00:00',
               '2009-02-21 10:00:00', '2009-02-21 11:00:00',
               '2009-02-21 12:00:00', '2009-02-21 13:00:00',
               '2009-02-21 14:00:00', '2009-02-21 15:00:00',
               '2009-02-21 16:00:00', '2009-02-21 17:00:00'],
              dtype='datetime64[us]', name='datetime', length=1241, freq=None)

### Intentar determinar la frecuencia de la serie con infer_freq()

Sólo funciona cuando la frecuencia es regular en los registros de la serie

In [ ]:
pd.infer_freq(weather.index) # se infiere que la frecuencia es horaria

'h'

### asfreq()   

1.- Tomando la primera muestra de cada frecuencia

2.- Elimina datos de la serie restantes

### resample() 

1.- Agrupando periodos de tiempo indicados

2.- Después aplica una función de agregación

### Remuestreo con asfreq()

Pasar de una frecuencia de 24 por hora -> 1 por dia

In [18]:
weather.asfreq('D') # Se ve que solo se conservan los datos del primer dia

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.40,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.70
2009-01-02 01:00:00,999.34,-4.44,268.77,-5.19,94.40,4.39,4.15,0.25,2.58,4.15,1293.47,0.28,1.00,148.10
2009-01-03 01:00:00,1002.39,-5.28,267.70,-6.35,92.10,4.12,3.79,0.33,2.36,3.78,1301.68,0.27,1.00,292.80
2009-01-04 01:00:00,992.19,-1.42,272.35,-5.61,73.00,5.50,4.02,1.49,2.52,4.05,1270.01,2.77,4.75,232.10
2009-01-05 01:00:00,984.74,-1.57,272.79,-2.58,92.80,5.44,5.05,0.39,3.20,5.13,1260.66,2.55,4.75,245.30
2009-01-06 01:00:00,997.71,-13.34,259.99,-15.46,83.90,2.18,1.83,0.35,1.14,1.83,1336.78,0.91,2.25,8.35
2009-01-07 01:00:00,994.14,-21.56,252.02,-23.54,83.80,1.08,0.91,0.18,0.57,0.91,1376.00,0.68,1.25,173.30
2009-01-08 01:00:00,999.20,-11.92,261.30,-13.19,90.20,2.44,2.20,0.24,1.37,2.21,1331.32,0.50,0.88,149.10
2009-01-09 01:00:00,1003.36,-14.46,258.45,-15.71,90.10,1.98,1.79,0.20,1.11,1.78,1350.20,0.38,0.75,175.80
2009-01-10 01:00:00,1003.55,-13.86,259.04,-15.13,90.00,2.09,1.88,0.21,1.16,1.87,1347.28,0.97,1.75,202.80
2009-01-11 01:00:00,1002.78,-11.77,261.18,-13.00,90.50,2.47,2.24,0.23,1.39,2.23,1335.30,0.58,1.00,167.60
2009-01-12 01:00:00,1002.67,-8.80,264.16,-10.67,86.20,3.13,2.70,0.43,1.68,2.70,1319.93,2.58,3.75,197.40
2009-01-13 01:00:00,993.01,-4.79,268.91,-9.90,67.23,4.28,2.87,1.40,1.80,2.89,1287.57,2.41,3.38,160.00
2009-01-14 01:00:00,987.44,-5.90,268.23,-9.04,78.30,3.93,3.08,0.85,1.94,3.12,1285.55,3.05,4.75,181.50
2009-01-15 01:00:00,990.47,0.57,274.48,-0.65,91.50,6.37,5.83,0.54,3.67,5.88,1257.71,1.26,2.75,225.80
2009-01-16 01:00:00,997.73,-4.10,269.24,-4.38,97.90,4.51,4.41,0.09,2.75,4.42,1289.62,1.18,1.88,199.00
2009-01-17 01:00:00,994.90,-2.57,270.98,-4.11,89.10,5.05,4.50,0.55,2.82,4.52,1278.67,2.79,3.75,190.10
2009-01-18 01:00:00,988.04,1.84,275.94,-0.15,86.60,6.98,6.04,0.93,3.81,6.11,1248.75,1.02,2.00,236.80
2009-01-19 01:00:00,979.19,1.96,276.78,-1.89,75.50,7.04,5.31,1.72,3.38,5.43,1237.31,1.97,3.13,232.80
2009-01-20 01:00:00,965.40,4.47,280.44,2.34,86.00,8.41,7.23,1.18,4.67,7.49,1207.92,1.95,2.75,202.20
2009-01-21 01:00:00,977.65,-2.91,272.00,-3.45,96.00,4.93,4.73,0.20,3.01,4.84,1257.92,0.90,1.50,208.10
2009-01-22 01:00:00,983.37,-3.98,270.47,-4.39,97.00,4.54,4.41,0.14,2.79,4.48,1270.50,0.99,2.00,169.00
2009-01-23 01:00:00,969.92,-1.23,274.31,-3.91,81.90,5.58,4.57,1.01,2.94,4.71,1240.33,3.86,6.25,178.70
2009-01-24 01:00:00,953.66,1.73,278.65,0.00,88.20,6.92,6.11,0.82,3.99,6.40,1205.62,4.74,6.38,206.10
2009-01-25 01:00:00,971.77,0.41,275.82,-1.70,85.70,6.29,5.39,0.90,3.46,5.55,1234.85,1.09,2.13,137.60
2009-01-26 01:00:00,975.25,-3.31,271.79,-3.80,96.40,4.78,4.61,0.17,2.94,4.73,1256.75,0.31,0.88,128.10
2009-01-27 01:00:00,981.26,-1.17,273.46,-1.68,96.30,5.61,5.40,0.21,3.43,5.50,1254.17,1.41,2.25,46.28
2009-01-28 01:00:00,990.87,-1.63,272.24,-1.63,100.00,5.42,5.42,0.00,3.41,5.47,1268.63,0.00,0.00,0.00
2009-01-29 01:00:00,995.23,-2.63,270.91,-4.48,87.00,5.03,4.38,0.65,2.74,4.40,1279.40,0.00,0.00,0.00
2009-01-30 01:00:00,998.88,-1.96,271.29,-4.78,80.90,5.29,4.28,1.01,2.67,4.28,1281.01,1.77,3.38,83.40
2009-01-31 01:00:00,997.13,-2.43,270.95,-3.79,90.30,5.11,4.61,0.50,2.88,4.62,1280.81,1.60,2.50,36.07
2009-02-01 01:00:00,989.11,-3.20,270.81,-5.30,85.30,4.82,4.11,0.71,2.59,4.16,1274.35,5.29,6.88,32.19
2009-02-02 01:00:00,982.48,-2.28,272.26,-4.53,84.40,5.17,4.36,0.81,2.76,4.44,1261.36,3.75,4.88,34.54
2009-02-03 01:00:00,975.96,-1.79,273.26,-2.71,93.40,5.35,5.00,0.35,3.19,5.12,1250.43,0.19,0.75,152.20
2009-02-04 01:00:00,972.38,-2.99,272.35,-3.38,97.10,4.90,4.76,0.14,3.05,4.89,1251.46,0.19,0.63,199.90
2009-02-05 01:00:00,972.65,0.17,275.50,-0.41,95.90,6.18,5.93,0.25,3.80,6.10,1236.81,1.26,3.00,135.20
2009-02-06 01:00:00,971.09,0.53,275.99,-1.14,88.50,6.35,5.62,0.73,3.61,5.78,1233.34,1.56,2.50,215.20
2009-02-07 01:00:00,963.24,-0.08,276.02,-2.19,85.60,6.07,5.20,0.87,3.36,5.40,1226.28,0.66,1.50,176.90
2009-02-08 01:00:00,966.08,1.97,277.85,0.75,91.60,7.04,6.45,0.59,4.16,6.68,1220.15,2.45,4.38,247.50
2009-02-09 01:00:00,980.69,-2.82,271.85,-5.42,82.20,4.96,4.08,0.88,2.59,4.16,1261.74,1.24,2.63,173.30
2009-02-10 01:00:00,972.28,-0.57,274.79,-1.96,90.30,5.86,5.29,0.57,3.39,5.44,1240.00,2.25,3.63,203.40
2009-02-11 01:00:00,970.37,0.39,275.91,-2.44,81.20,6.28,5.10,1.18,3.28,5.26,1233.30,3.53,6.00,247.60
2009-02-12 01:00:00,983.23,-0.30,274.18,-1.87,89.10,5.97,5.32,0.65,3.37,5.41,1252.74,0.90,1.50,252.40
2009-02-13 01:00:00,989.14,-2.30,271.71,-4.78,83.00,5.16,4.28,0.88,2.70,4.33,1270.08,2.23,3.63,261.90
2009-02-14 01:00:00,989.24,-0.85,273.15,-1.67,94.10,5.74,5.40,0.34,3.40,5.46,1262.90,0.97,2.13,252.40
2009-02-15 01:00:00,1000.30,-6.23,266.90,-8.10,86.50,3.83,3.31,0.52,2.06,3.31,1303.83,1.69,2.25,248.60
2009-02-16 01:00:00,993.08,-2.50,271.20,-4.02,89.20,5.08,4.53,0.55,2.84,4.56,1275.97,4.28,7.13,200.80
2009-02-17 01:00:00,986.78,-0.69,273.51,-1.08,97.20,5.81,5.64,0.16,3.57,5.72,1258.90,0.80,1.63,156.60
2009-02-18 01:00:00,999.30,-4.75,268.46,-6.38,88.30,4.29,3.79,0.50,2.36,3.79,1295.11,1.56,3.25,347.50
2009-02-19 01:00:00,998.46,-8.97,264.31,-10.26,90.30,3.09,2.79,0.30,1.74,2.80,1315.18,1.31,1.88,221.70
2009-02-20 01:00:00,996.63,-2.35,271.07,-3.54,91.50,5.14,4.70,0.44,2.94,4.72,1279.74,1.72,3.13,182.50
2009-02-21 01:00:00,999.18,1.55,274.77,1.04,96.40,6.83,6.59,0.25,4.11,6.59,1263.92,1.59,2.13,255.40

In [ ]:
weather.asfreq('D').index.freq # Se indica que la frecuencia se cambio a dias

Primer muestra del Lunes de cada semana

In [ ]:
weather.asfreq('W-MON')

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-05 01:00:00,984.74,-1.57,272.79,-2.58,92.8,5.44,5.05,0.39,3.20,5.13,1260.66,2.55,4.75,245.30
2009-01-12 01:00:00,1002.67,-8.80,264.16,-10.67,86.2,3.13,2.70,0.43,1.68,2.70,1319.93,2.58,3.75,197.40
2009-01-19 01:00:00,979.19,1.96,276.78,-1.89,75.5,7.04,5.31,1.72,3.38,5.43,1237.31,1.97,3.13,232.80
2009-01-26 01:00:00,975.25,-3.31,271.79,-3.80,96.4,4.78,4.61,0.17,2.94,4.73,1256.75,0.31,0.88,128.10
2009-02-02 01:00:00,982.48,-2.28,272.26,-4.53,84.4,5.17,4.36,0.81,2.76,4.44,1261.36,3.75,4.88,34.54
2009-02-09 01:00:00,980.69,-2.82,271.85,-5.42,82.2,4.96,4.08,0.88,2.59,4.16,1261.74,1.24,2.63,173.30
2009-02-16 01:00:00,993.08,-2.50,271.20,-4.02,89.2,5.08,4.53,0.55,2.84,4.56,1275.97,4.28,7.13,200.80

In [23]:
weather.asfreq('W-MON').index.freq

Muestras cada 2 horas

In [25]:
weather.asfreq('2h')

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0
2009-01-01 07:00:00,998.33,-9.17,264.12,-10.10,92.9,3.04,2.83,0.22,1.76,2.83,1315.98,2.08,2.88,348.8
2009-01-01 09:00:00,999.69,-7.66,265.52,-8.84,91.2,3.43,3.13,0.30,1.95,3.13,1310.14,0.34,0.63,202.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-02-21 09:00:00,1001.27,0.15,273.21,-0.45,95.7,6.18,5.91,0.27,3.68,5.90,1273.35,1.14,1.88,255.6
2009-02-21 11:00:00,1001.53,1.08,274.12,0.15,93.5,6.61,6.18,0.43,3.84,6.17,1269.27,0.97,2.63,251.5
2009-02-21 13:00:00,1001.53,1.43,274.47,0.57,94.0,6.77,6.37,0.41,3.96,6.36,1267.55,1.18,2.88,243.0
2009-02-21 15:00:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.7
2009-02-21 17:00:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.0

In [27]:
weather.asfreq('2h').index.freq

Siempre se está pasando a una frecuencia de mayor tamaño, porque hay datos disponibles, pero si se quire pasar a una frecuencia menor, no van a existir esos datos y se van a inventar con espacios vacíos.

Ejemplo pasando de frecuencia de 1 hora -> media hora

In [29]:
weather.asfreq('30min')

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 01:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 02:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-02-21 15:00:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.7
2009-02-21 15:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-02-21 16:00:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.8
2009-02-21 16:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-02-21 17:00:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.0

In [30]:
weather.asfreq('30min').index.freq

Se pueden rellenar con valores replicados:

* Futuros: 'ffill'

* Pasados: 'bfill'

In [31]:
weather.asfreq('30min', method='ffill')

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 01:30:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 02:30:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-02-21 15:00:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.7
2009-02-21 15:30:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.7
2009-02-21 16:00:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.8
2009-02-21 16:30:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.8
2009-02-21 17:00:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.0

In [33]:
weather.asfreq('30min', method='bfill')

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 01:30:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 02:30:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-02-21 15:00:00,1001.39,1.72,274.77,0.63,92.4,6.92,6.39,0.53,3.98,6.38,1266.00,1.66,2.63,254.7
2009-02-21 15:30:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.8
2009-02-21 16:00:00,1001.42,1.95,275.00,0.43,89.6,7.03,6.30,0.73,3.92,6.29,1265.03,1.87,3.50,280.8
2009-02-21 16:30:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.0
2009-02-21 17:00:00,1001.04,1.92,275.00,0.40,89.6,7.02,6.29,0.73,3.92,6.28,1264.71,1.41,2.38,253.0

### Remuestreo con resample()

In [ ]:
weather.resample('24h').mean() # Toma el primer bloque de 24 hrs, lo promedia y eso es un nuevo registro

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01,999.180000,-6.854783,266.367826,-8.072609,90.991304,3.678696,3.341304,0.337826,2.081304,3.342174,1305.450000,0.775217,1.372609,196.326087
2009-01-02,999.549167,-3.731250,269.463333,-4.825000,92.108333,4.638750,4.267500,0.372083,2.659167,4.268333,1290.302917,1.417917,2.211250,119.558750
2009-01-03,998.716667,-5.284583,267.976250,-9.013333,76.588750,4.180000,3.109583,1.069167,1.939167,3.113333,1297.390833,1.154167,2.058750,199.033333
2009-01-04,988.639167,-1.381250,272.670000,-2.980000,88.950000,5.521667,4.911250,0.609583,3.096250,4.968750,1264.838750,1.661667,3.455417,209.383333
2009-01-05,990.178333,-4.673750,269.251667,-6.565000,86.545833,4.416667,3.865833,0.550833,2.435417,3.908333,1283.098750,3.978750,6.325000,108.381250
2009-01-06,997.093750,-15.283750,258.090833,-17.437083,83.620833,1.886250,1.563750,0.322500,0.976667,1.569583,1346.271250,1.251667,2.184583,167.866250
2009-01-07,993.430417,-15.888750,257.756667,-17.713750,85.616667,1.962917,1.705417,0.258750,1.068333,1.713750,1344.994167,0.739167,1.460417,155.592917
2009-01-08,1002.891667,-9.504167,263.437083,-11.232083,87.408333,3.034167,2.616250,0.417500,1.624167,2.608333,1323.930000,0.795417,1.330833,174.595833
2009-01-09,1003.124583,-12.216250,260.711250,-14.534167,83.562083,2.509167,2.020417,0.490833,1.252500,2.012917,1338.486250,0.649167,1.246250,162.758750
2009-01-10,1002.996250,-10.745000,262.192083,-13.359583,81.992917,2.827917,2.225000,0.605000,1.380833,2.217500,1330.728333,0.705833,1.336667,176.307500
2009-01-11,1003.991667,-8.654167,264.204583,-11.101250,83.358750,3.307500,2.652083,0.655417,1.645000,2.641667,1321.240000,1.364167,2.387917,171.245833
2009-01-12,998.668333,-5.407083,267.858750,-9.770833,72.633333,4.252500,2.925833,1.326667,1.824583,2.930000,1298.210000,2.414167,3.670000,191.733333
2009-01-13,990.254583,-1.637917,272.284167,-8.231667,61.486250,5.563750,3.291667,2.271250,2.071667,3.324167,1269.090000,2.407917,3.716250,181.787500
2009-01-14,987.547917,-4.755833,269.367917,-7.708750,80.349167,4.432917,3.509167,0.925417,2.212917,3.552500,1280.249583,0.828333,1.673333,163.620833
2009-01-15,993.978750,0.053333,273.686667,-1.302917,90.808333,6.185000,5.569583,0.617500,3.492917,5.602917,1264.760417,0.678750,1.335000,142.939583
2009-01-16,997.598333,-2.832083,270.515833,-3.846250,92.875000,5.001250,4.607083,0.393333,2.877500,4.620000,1283.380417,1.531250,2.320000,196.754167
2009-01-17,992.251667,-0.016667,273.751667,-1.817917,87.666667,6.143333,5.375417,0.768333,3.377083,5.417083,1262.975833,2.230833,3.507917,174.075000
2009-01-18,979.307917,2.543750,277.359583,-0.097500,82.969167,7.369167,6.066667,1.300417,3.863750,6.196250,1234.545833,2.836667,4.387500,198.379167
2009-01-19,972.985417,2.526250,277.857083,-0.724167,79.150000,7.353750,5.832917,1.522500,3.739583,5.999167,1226.747500,3.465417,5.341667,188.479167
2009-01-20,971.101250,3.315833,278.806667,0.034583,79.333333,7.853750,6.164583,1.689167,3.960000,6.351667,1220.797083,1.959167,3.106667,198.304583
2009-01-21,980.095417,-1.565833,273.160833,-2.589167,92.804167,5.475417,5.056667,0.417500,3.214583,5.158333,1254.702917,0.693750,1.272917,170.698333
2009-01-22,978.611667,-1.141250,273.708750,-3.162500,86.792083,5.692083,4.842500,0.850417,3.082917,4.947083,1251.033750,2.807500,4.236667,176.558333
2009-01-23,955.831667,1.379583,278.120417,-2.015833,78.360833,6.858333,5.363333,1.496667,3.503333,5.619583,1210.479167,5.181667,7.731250,183.833333
2009-01-24,960.802917,2.677917,279.012500,-1.564167,74.277083,7.433750,5.464583,1.970833,3.547083,5.688333,1210.837083,2.935000,4.476667,219.945833
2009-01-25,973.989167,0.975833,276.210417,-1.741250,82.835417,6.642083,5.381667,1.260833,3.443750,5.526250,1235.213333,0.930833,1.700417,169.554167
2009-01-26,977.137500,-3.325000,271.625833,-3.788750,96.575000,4.799583,4.634583,0.165417,2.954167,4.742083,1259.263333,1.452083,2.205833,100.529583
2009-01-27,985.937083,-1.335000,272.930833,-1.483750,98.908333,5.539167,5.477917,0.060833,3.463333,5.556250,1260.883750,2.250000,3.294583,27.815417
2009-01-28,992.747083,-2.468750,271.257083,-2.985833,96.266667,5.095000,4.905833,0.188333,3.080833,4.942500,1275.210417,0.000000,0.000000,0.000000
2009-01-29,996.800000,-2.384167,271.024583,-4.032500,88.445833,5.126667,4.529583,0.597917,2.831667,4.543750,1280.210417,1.520000,2.627083,42.807500
2009-01-30,998.938750,-2.396667,270.845833,-5.235417,80.787500,5.120833,4.136667,0.984583,2.579583,4.140000,1283.212083,2.124583,3.710833,67.490000
2009-01-31,994.514167,-1.997500,271.590417,-3.660000,88.475000,5.277083,4.664583,0.610417,2.922500,4.690417,1275.385000,2.555417,3.981250,40.484583
2009-02-01,985.880000,-3.364583,270.895833,-5.772083,83.400000,4.765417,3.968750,0.795833,2.508333,4.027500,1271.039167,4.055000,6.480833,44.157917
2009-02-02,980.070417,-0.767917,273.967083,-3.735000,80.522500,5.861667,4.673333,1.188333,2.971667,4.769583,1251.269583,1.476667,2.524583,120.764583
2009-02-03,973.928333,0.045000,275.277500,-1.797917,88.062083,6.264167,5.378750,0.886250,3.442500,5.523333,1239.410833,0.465833,0.956667,129.834583
2009-02-04,972.083333,-1.059583,274.312917,-2.267500,91.975000,5.785833,5.219583,0.566250,3.347083,5.369167,1242.169167,0.784583,1.445417,167.290417
2009-02-05,972.013333,1.880833,277.281667,-0.327500,86.061667,7.100833,5.976250,1.125000,3.833333,6.149167,1228.385000,1.853750,2.841667,179.995833
2009-02-06,968.448333,2.575417,278.276250,-0.292500,82.141250,7.522500,6.005000,1.519583,3.865417,6.199583,1220.838333,1.519167,2.470833,180.685417
2009-02-07,961.860000,1.387917,277.617500,-0.736250,86.071667,6.850833,5.823333,1.026667,3.775833,6.055833,1217.776667,1.138750,2.065000,204.724583
2009-02-08,973.435833,1.143333,276.424583,-2.942500,74.796667,6.652083,4.970417,1.683333,3.184583,5.109167,1233.894583,1.985417,3.872500,251.408333
2009-02-09,980.039583,-0.212917,274.524167,-4.551667,73.101667,6.062500,4.357500,1.705000,2.770000,4.444167,1248.775417,3.369583,4.830000,191.208333
2009-02-10,964.195417,2.459167,278.512083,0.119583,84.972917,7.391667,6.205000,1.184583,4.015833,6.438750,1215.835833,5.013750,7.867500,203.891667
2009-02-11,979.124583,0.313333,275.130000,-2.936250,79.122500,6.255833,4.925833,1.330417,3.136667,5.032917,1244.875000,3.027500,5.830000,264.991667
2009-02-12,986.662917,-1.365833,272.840833,-4.908750,77.280833,5.542500,4.262083,1.281667,2.692083,4.320833,1262.571250,2.169583,3.877917,213.595417
2009-02-13,989.271667,-1.383333,272.617917,-3.679583,84.780417,5.560833,4.673750,0.885833,2.944167,4.726250,1265.830000,1.591250,2.841250,239.475000
2009-02-14,994.782083,-3.536250,270.030417,-5.554583,85.912500,4.730000,4.078750,0.651250,2.555000,4.101667,1283.347500,1.710417,3.023333,198.207500
2009-02-15,998.812500,-4.338333,268.915000,-7.200000,80.929167,4.491250,3.571667,0.921667,2.227500,3.576250,1292.715417,2.206667,3.507083,200.527500
2009-02-16,991.124167,0.136250,273.995000,-1.732083,87.300000,6.210833,5.404167,0.807917,3.398750,5.454583,1260.803333,2.245833,3.908750,227.479167
2009-02-17,991.095000,-2.317917,271.540417,-4.242083,87.110833,5.185000,4.557083,0.626667,2.867917,4.602917,1272.622083,2.767500,4.351250,90.214583
2009-02-18,999.420000,-4.084583,269.122083,-7.330000,78.722500,4.537917,3.527500,1.011250,2.198750,3.528333,1292.215833,1.513333,2.752500,224.796250
2009-02-19,997.885417,-4.697083,268.626250,-8.822500,74.367083,4.529583,3.172917,1.356667,1.980000,3.180417,1293.699583,1.705833,2.773333,197.620833
2009-02-20,996.676250,0.190833,273.611667,-0.634583,94.191667,6.235833,5.868333,0.367917,3.669583,5.887083,1267.393333,1.813333,3.043750,212.400000
2009-02-21,1000.655000,1.090000,274.197778,0.331667,94.688889,6.615556,6.260000,0.356667,3.900000,6.255556,1268.065556,1.475556,2.691667,257.205556

### Ejercicio práctico

Tomar sólo la variable temperatura T (degC) y por cada periodo de 24 horas mostrar el promedio, el máximo y el mínimo de la serie de tiempo

In [43]:
weather = pd.read_csv('datos/weather_dataset.csv',
                        parse_dates = ['datetime'],
                        index_col = 'datetime')
weather = weather.loc[:, ['T (degC)']]
weather.head()

                     T (degC)
datetime
2009-01-01 01:00:00     -8.05
2009-01-01 02:00:00     -8.88
2009-01-01 03:00:00     -8.81
2009-01-01 04:00:00     -9.05
2009-01-01 05:00:00     -9.63

In [46]:
weather.resample('24h').agg(['mean', 'min', 'max'])

             T (degC)
                 mean    min    max
datetime
2009-01-01  -6.854783  -9.67  -4.47
2009-01-02  -3.731250  -4.96  -2.12
2009-01-03  -5.284583  -9.46  -0.82
2009-01-04  -1.381250  -2.22  -0.70
2009-01-05  -4.673750 -11.72  -1.47
2009-01-06 -15.283750 -20.85 -10.97
2009-01-07 -15.888750 -22.76  -7.75
2009-01-08  -9.504167 -13.25  -4.27
2009-01-09 -12.216250 -17.02  -3.69
2009-01-10 -10.745000 -15.46  -2.24
2009-01-11  -8.654167 -13.40  -0.33
2009-01-12  -5.407083 -10.76   2.32
2009-01-13  -1.637917  -5.19   4.89
2009-01-14  -4.755833 -10.21   0.37
2009-01-15   0.053333  -3.57   4.52
2009-01-16  -2.832083  -5.21   1.12
2009-01-17  -0.016667  -2.57   2.55
2009-01-18   2.543750   0.04   5.05
2009-01-19   2.526250   0.75   4.27
2009-01-20   3.315833  -2.66   6.68
2009-01-21  -1.565833  -3.24   1.30
2009-01-22  -1.141250  -3.98   3.05
2009-01-23   1.379583  -1.51   5.68
2009-01-24   2.677917   0.54   5.30
2009-01-25   0.975833  -2.79   5.62
2009-01-26  -3.325000  -5.77  -1.10
2009-01-27  -1.335000  -1.75  -1.09
2009-01-28  -2.468750  -3.10  -1.63
2009-01-29  -2.384167  -3.36  -1.74
2009-01-30  -2.396667  -3.03  -1.90
2009-01-31  -1.997500  -2.73  -0.87
2009-02-01  -3.364583  -4.41  -2.58
2009-02-02  -0.767917  -5.01   3.71
2009-02-03   0.045000  -3.28   7.64
2009-02-04  -1.059583  -4.83   4.43
2009-02-05   1.880833  -1.46   6.34
2009-02-06   2.575417  -1.13   8.96
2009-02-07   1.387917  -2.26   5.82
2009-02-08   1.143333  -1.34   3.03
2009-02-09  -0.212917  -2.98   3.01
2009-02-10   2.459167  -0.85   7.06
2009-02-11   0.313333  -0.77   2.07
2009-02-12  -1.365833  -3.04   1.44
2009-02-13  -1.383333  -4.72   1.18
2009-02-14  -3.536250  -5.70  -0.69
2009-02-15  -4.338333  -8.44  -0.94
2009-02-16   0.136250  -2.94   2.30
2009-02-17  -2.317917  -5.29   0.16
2009-02-18  -4.084583  -7.12  -0.47
2009-02-19  -4.697083 -11.12   1.50
2009-02-20   0.190833  -2.77   2.32
2009-02-21   1.090000   0.15   1.95

In [50]:
def mean_min_max(serie):
    valores = [serie.mean(), serie.min(), serie.max()]
    variables = ['mean', 'min', 'max']
    return pd.DataFrame(data = valores, index = variables)

weather.resample('24h').apply(mean_min_max)

      T (degC)
mean -6.854783
min  -9.670000
max  -4.470000
mean -3.731250
min  -4.960000
...        ...
min  -2.770000
max   2.320000
mean  1.090000
min   0.150000
max   1.950000

[156 rows x 1 columns]