### Desplazamiento en el tiempo

Recorrer los valores en el tiempo para decidir cuando van a iniciar en otro punto diferente

In [3]:
import numpy as np
import pandas as pd

valores = np.arange(10)
indice = pd.date_range('2023-01-01', periods=10, freq = '24h')
df = pd.DataFrame(data = {'valores': valores}, index = indice)
df

            valores
2023-01-01        0
2023-01-02        1
2023-01-03        2
2023-01-04        3
2023-01-05        4
2023-01-06        5
2023-01-07        6
2023-01-08        7
2023-01-09        8
2023-01-10        9

In [5]:
df.shift(5) # Numero de filas que queremos desplazar

            valores
2023-01-01      NaN
2023-01-02      NaN
2023-01-03      NaN
2023-01-04      NaN
2023-01-05      NaN
2023-01-06      0.0
2023-01-07      1.0
2023-01-08      2.0
2023-01-09      3.0
2023-01-10      4.0

In [6]:
df.shift(-3)

            valores
2023-01-01      3.0
2023-01-02      4.0
2023-01-03      5.0
2023-01-04      6.0
2023-01-05      7.0
2023-01-06      8.0
2023-01-07      9.0
2023-01-08      NaN
2023-01-09      NaN
2023-01-10      NaN

para recorrer el indice y mantener los valres, entonces se usa el parpametro de frecuencias

In [13]:
df.shift(2, freq = '24h')

            valores
2023-01-03        0
2023-01-04        1
2023-01-05        2
2023-01-06        3
2023-01-07        4
2023-01-08        5
2023-01-09        6
2023-01-10        7
2023-01-11        8
2023-01-12        9