### Manejo de datos faltantes

In [3]:
import pandas as pd

co2 = pd.read_csv('datos/co2_faltantes.csv',
                    parse_dates=['año'],
                    index_col = 'año')
co2.head()

               co2
año
1750-01-01  0.0125
1760-01-01  0.0128
1770-01-01     NaN
1780-01-01  0.0169
1790-01-01  0.0206

In [5]:
clicks = pd.read_csv('datos/clicks_faltantes_marcas.csv',
                        parse_dates = ['fecha'],
                        index_col = 'fecha')
clicks.head()

/tmp/ipykernel_188606/2517434643.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clicks = pd.read_csv('datos/clicks_faltantes_marcas.csv',

               precio  ubicación   clicks
fecha
2008-04-01  43.155647          2  18784.0
2008-04-02  43.079056          1  24738.0
NaT         43.842609          2  15209.0
2008-04-04  43.382794          2  14320.0
2008-04-05  43.941176          1  11974.0

In [6]:
clicks = pd.read_csv('datos/clicks_faltantes_marcas_ocultas.csv',
                        parse_dates = ['fecha'],
                        index_col = 'fecha')
clicks.head()

/tmp/ipykernel_188606/4073867135.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clicks = pd.read_csv('datos/clicks_faltantes_marcas_ocultas.csv',

               precio  ubicación   clicks
fecha
2008-04-01  43.155647          2  18784.0
2008-04-02  43.079056          1  24738.0
2008-04-03  43.842609          2  15209.0
2008-04-05  43.941176          1  11974.0
2008-04-06  44.403936          1  11007.0

In [7]:
clicks = pd.read_csv('datos/clicks_faltantes_multiples.csv',
                        parse_dates = ['fecha'],
                        index_col = 'fecha')
clicks.head()

/tmp/ipykernel_188606/3495471139.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clicks = pd.read_csv('datos/clicks_faltantes_multiples.csv',

               precio  ubicación clicks
fecha
2008-04-01  43.155647        2.0  18784
2008-04-02  43.079056        1.0  24738
NaT         43.842609        NaN  15209
NaT               NaN        1.0  14018
NaT         43.941176        1.0  11974